spring:
  application:
    name: samplemicroservices
  
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

     
   
      
      